theme: jekyll-theme-minimal
title : Penetation testing blog
author: Sunil Kumar Sathyanarayan
Email : pentestvizard@pm.me
description: This blog covers lot of hacking and penetration testing related blog posts which I feel is interesting to share.
logo: pentestvizard-logo.png
