theme : minimal-mistakes-jekyll
title : Penetation testing blog by Sunil Sathyanarayan
author: Sunil Sathyanarayan
Email : pentestvizard@pm.me
description: This blog covers lot of hacking and penetration testing related blog posts which I feel is interesting to share.
logo: Pentest_vizard_final_round.png
